App_Order/urls.py
from django.urls import path
from App_Order import views

app_name='App_Order'

urlpatterns = [
path('add/<pk>/', views.add_to_cart, name='add'),
path('cart/', views.cart_view, name='cart'),
path('remove/<pk>/', views.remove_from_cart, name='remove'),
path('increase_cart/<pk>/', views.increase_cart, name='increase_cart'),
path('decrease_cart/<pk>/', views.decrease_cart, name='decrease_cart'),
]

App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = 'App_Payment'

urlpatterns = [ 
 path('checkout/', views.checkout, name='checkout'),
 path('payment/', views.payment, name='payment'),
 path('status/', views.complete, name='complete'),
 path('purchase/<val_id>/<tran_id>', views.purchase, name='purchase'),
 path('order_view/', views.order_view, name='order'),
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views


app_name = 'App_Shop'


urlpatterns = [
path('', views.Home.as_view(), name='home'),
path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
]

SDeCommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('', include('App_Shop.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Order/models.py
from django.db import models
from django.conf import settings
from App_Shop.models import Product 
# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart')
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.quantity} of {self.item}'
    
    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '.2f')
        return float_total  # 100.00
    

class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=100, blank=True, null=True)
    orderId = models.CharField(max_length=100, blank=True, null=True)

    def get_total(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        return total
    

App_Order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from App_Order.models import Cart, Order
from App_Shop.models import Product

# Create your views here.

@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item[0].quantity += 1
            order_item[0].save()
            messages.info(request, "This item quantity was updated.")
            return redirect('App_Shop:home')
        else:
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect('App_Shop:home')
    else:
        order = Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        messages.info(request, "This item was added to your cart.")
        return redirect('App_Shop:home')

@login_required
def cart_view(rquest):
   carts = Cart.objects.filter(user=rquest.user, purchased=False) 
   orders =Order.objects.filter(user=rquest.user, ordered=False)
   if carts.exists() and orders.exists():
       order = orders[0]
       return render(rquest, 'App_Order/cart.html', context={'carts':carts, 'order':order})
   else:
       messages.warning(rquest, "You do not have any item in your cart.")
       return redirect('App_Shop:home')
   
@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            messages.warning(request, "This item was removed from your cart.")
            return redirect('App_Order:cart')
        else:
            messages.info(request, "This item was not in your cart.")
            return redirect('App_Shop:home', pk=pk)
    else:
        messages.warning(request, "You do not have any active order.")
        return redirect('App_Shop:home')
    

@login_required
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get(item=item, user=request.user, purchased=False)
    if order_item:
        order_item.quantity += 1
        order_item.save()
        messages.info(request, f"{item.name} item quantity was updated.")
        return redirect('App_Order:cart')
    else:
        messages.info(request, "This item was not in your cart.")
        return redirect('App_Shop:home')
    
@login_required
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get(item=item, user=request.user, purchased=False)
    if order_item:
        if order_item.quantity > 1:
            order_item.quantity -= 1
            order_item.save()
            messages.info(request, f"{item.name} item quantity was updated.")
        else:
            order_item.delete()
            messages.warning(request, "This item was removed from your cart.")
        return redirect('App_Order:cart')
    else:
        messages.info(request, "This item was not in your cart.")
        return redirect('App_Shop:home')

templates/App_Order/cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Home{% endblock %}
{% block body_block %}
<div class="container my-5">
    <div class="my-5">
        <h2 class="mb-4">My Cart</h2>
        <table class="table table-bordered table-hover align-middle">
            <thead class="table-dark">
                <tr>
                    <th scope="col" width="10%">#</th>
                    <th scope="col">Product Name</th>
                    <th scope="col" class="text-center" width="25%">Quantity</th>
                    <th scope="col" class="text-end" width="20%">Price</th>
                    <th scope="col" class="text-center" width="15%">Remove</th>
                </tr>
            </thead>
            <tbody>
                {% for cart in carts %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ cart.item.name }}</td>
                    <td class="text-center">
                        <div class="d-flex align-items-center justify-content-center">
                            <a href="{% url 'App_Order:decrease_cart' pk=cart.item.pk %}" class="btn btn-sm btn-outline-danger me-2"><i class="fa-solid fa-minus"></i></a>
                            <span class="mx-2">{{ cart.quantity }}</span>
                            <a href="{% url 'App_Order:increase_cart' pk=cart.item.pk %}" class="btn btn-sm btn-outline-success ms-2"><i class="fa-solid fa-plus"></i></a>
                        </div>
                    </td>
                    <td class="text-end">&#2547;{{ cart.get_total }}</td>
                    <td class="text-center">
                        <a href="{% url 'App_Order:remove' pk=cart.item.pk %}" class="btn btn-sm btn-outline-danger"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
                <tr class="fw-bold">
                    <td></td>
                    <td colspan="2" class="text-end">Total</td>
                    <td class="text-end">&#2547;{{ order.get_total|floatformat:2 }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="5" class="text-end">
                        <div class="d-flex justify-content-end gap-3">
                            <a href="{% url 'App_Shop:home' %}" class="btn btn-warning btn-m">
                                <i class="fa-solid fa-shopping-cart"></i> Continue Shopping
                            </a>
                            <a href="{% url 'App_Payment:checkout'  %}" class="btn btn-success btn-m">
                                <i class="fa-solid fa-credit-card"></i> Checkout
                            </a>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}